[DROOLS-178] fix NoSuchMethodError at runtime due to eval in query using backward chaining (cherry picked from commit 51b3d7794fd1f50bea2a6888db6aeafefdc8da74)