BZ-1187237 - org.jbpm.kie.services.test.RuntimeDataServiceImplTest.testGetProcessesSortByProcessVersion fails on OracleJDK8 due to: expected:<[org.jboss.qa.bpms.Human]Task> but was:<[User]Task>