BZ-1098018 - NoClassDefFoundError of dependent jar class during process execution - load transitive dependencies of projects
(cherry picked from commit 604f86c13596bc0d046753cacd8cd44221e09b60)